import { Product } from "./types";

export const defaultProducts: Product[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    currency: "CAD",
    description: "Best for simple tax returns with only salary or student income and no additional deductions.",
    bestFor: ["Students", "Employees", "Simple Returns"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: false,
      donations: false,
      employmentExpenses: false,
      investmentIncome: false,
      capitalGains: false,
      foreignIncome: false,
      rentalIncome: false,
      freelanceIncome: false,
      gigWorkIncome: false,
      businessExpenses: false,
      homeOfficeExpenses: false,
      vehicleExpenses: false,
      expertHelp: false,
      fullService: false,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "deluxe",
    name: "Deluxe",
    price: 30,
    currency: "CAD",
    description: "Great for families and individuals claiming common deductions like medical expenses and donations.",
    bestFor: ["Families", "Homeowners", "Charitable Donors"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: true,
      donations: true,
      employmentExpenses: true,
      investmentIncome: false,
      capitalGains: false,
      foreignIncome: false,
      rentalIncome: false,
      freelanceIncome: false,
      gigWorkIncome: false,
      businessExpenses: false,
      homeOfficeExpenses: false,
      vehicleExpenses: false,
      expertHelp: false,
      fullService: false,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "premier",
    name: "Premier",
    price: 50,
    currency: "CAD",
    description: "Designed for investors, property owners, and individuals with foreign income or capital gains.",
    bestFor: ["Investors", "Landlords", "Foreign Income Earners"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: true,
      donations: true,
      employmentExpenses: true,
      investmentIncome: true,
      capitalGains: true,
      foreignIncome: true,
      rentalIncome: true,
      freelanceIncome: false,
      gigWorkIncome: false,
      businessExpenses: false,
      homeOfficeExpenses: false,
      vehicleExpenses: false,
      expertHelp: false,
      fullService: false,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "self-employed",
    name: "Self-Employed",
    price: 70,
    currency: "CAD",
    description: "Tailored for freelancers, gig workers, sole proprietors, and contractors reporting business expenses.",
    bestFor: ["Freelancers", "Gig Workers", "Sole Proprietors"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: true,
      donations: true,
      employmentExpenses: true,
      investmentIncome: true,
      capitalGains: true,
      foreignIncome: true,
      rentalIncome: true,
      freelanceIncome: true,
      gigWorkIncome: true,
      businessExpenses: true,
      homeOfficeExpenses: true,
      vehicleExpenses: true,
      expertHelp: false,
      fullService: false,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "expert-assist",
    name: "Expert Assist",
    price: 120,
    currency: "CAD",
    description: "Get live chat, video consultation, and a final review from a tax professional on your personal tax return.",
    bestFor: ["Need Reassurance", "Complex Situations", "Live Support"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: true,
      donations: true,
      employmentExpenses: true,
      investmentIncome: true,
      capitalGains: true,
      foreignIncome: true,
      rentalIncome: true,
      freelanceIncome: true,
      gigWorkIncome: true,
      businessExpenses: true,
      homeOfficeExpenses: true,
      vehicleExpenses: true,
      expertHelp: true,
      fullService: false,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "expert-full-service",
    name: "Expert Full Service",
    price: 250,
    currency: "CAD",
    description: "Hand off your tax return completely. A dedicated tax professional will prepare, review, and file it for you.",
    bestFor: ["Busy Professionals", "Hands-off Filers", "Complete Delegation"],
    supports: {
      salaryIncome: true,
      studentIncome: true,
      medicalExpenses: true,
      donations: true,
      employmentExpenses: true,
      investmentIncome: true,
      capitalGains: true,
      foreignIncome: true,
      rentalIncome: true,
      freelanceIncome: true,
      gigWorkIncome: true,
      businessExpenses: true,
      homeOfficeExpenses: true,
      vehicleExpenses: true,
      expertHelp: true,
      fullService: true,
      corporateFiling: false,
      nilCorporateReturn: false,
    },
  },
  {
    id: "business-corporate",
    name: "Business Corporate",
    price: 400,
    currency: "CAD",
    description: "Complete corporate tax preparation and filing for incorporated businesses with active revenue.",
    bestFor: ["Incorporated Startups", "Small Businesses", "Corporate Filers"],
    supports: {
      salaryIncome: false,
      studentIncome: false,
      medicalExpenses: false,
      donations: false,
      employmentExpenses: false,
      investmentIncome: false,
      capitalGains: false,
      foreignIncome: false,
      rentalIncome: false,
      freelanceIncome: false,
      gigWorkIncome: false,
      businessExpenses: true,
      homeOfficeExpenses: true,
      vehicleExpenses: true,
      expertHelp: true,
      fullService: true,
      corporateFiling: true,
      nilCorporateReturn: false,
    },
  },
  {
    id: "nil-corporate-return",
    name: "Nil Corporate Return",
    price: 175,
    currency: "CAD",
    description: "Specialized filing for incorporated companies with no active revenue, operations, or transactions during the tax year.",
    bestFor: ["Inactive Corporations", "Holding Companies", "Pre-revenue Startups"],
    supports: {
      salaryIncome: false,
      studentIncome: false,
      medicalExpenses: false,
      donations: false,
      employmentExpenses: false,
      investmentIncome: false,
      capitalGains: false,
      foreignIncome: false,
      rentalIncome: false,
      freelanceIncome: false,
      gigWorkIncome: false,
      businessExpenses: false,
      homeOfficeExpenses: false,
      vehicleExpenses: false,
      expertHelp: true,
      fullService: true,
      corporateFiling: true,
      nilCorporateReturn: true,
    },
  },
];

export const products = defaultProducts;
